### ISSUE TITLE
Core Refactor Roadmap

### ISSUE THREAD

**Issue by littensy** [littensy/slither#32]
### Core

- [x] Start features via import side-effects
- [x] Merge `server/save` and `server/players` feature folders
- [x] Omit "-service" suffix from services

### UI & Logic

- [x] ~~Use new `rem` functionality~~ syntax too ambiguous
- [x] Clean up sounds module

### Issues

- [x] #30
- [x] #33
