### ISSUE TITLE
Reward players for hitting milestones

### ISSUE THREAD

**Issue by littensy** [littensy/slither#41]
Reward players with money for hitting milestones, maintaining placements, or other criteria.

### 🐍 Lifetime

Triggered on an event at most once per life.

- [x] Scores 1,000 → 5,000 → 10,000 → 20,000 → 50,000 → 100,000
- [x] Taking first-, second-, or third-place

### ⏰ Periodic

Triggered at a specific interval while the criteria is met.

- [x] Maintain first-, second-, or third-place

### 🍀 Event

Triggered immediately on an event, no limit.

- [x] Defeat a player, reward scaled with their length
